### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PandaWhoCodes**
Added 
1. Improving your code with modern idioms - under tutorials
2. Removed thenewboston.com links - They are no longer operational

### CODE REVIEW

**Comment by quobit** [comment]
It'd be useful to change the New Boston links by the YouTube playlist URL counterpart

**Comment by PandaWhoCodes** [comment]
let me do that and update this pull request.

**Comment by PandaWhoCodes** [comment]
Updated Links
Removed 404 links
Replaced some 404 links with mirrors
Tried fixing most of the errors here- https://travis-ci.org/quobit/awesome-python-in-education/builds/543584678

**Comment by PandaWhoCodes** [comment]
Removed duplicates
Removed 2 Oriely links since it's no longer free
2 Python3 Cheatsheet with same content - removed 1 with 404(https://perso.limsi.fr/) kept the other one.

Reference for changes - https://travis-ci.org/quobit/awesome-python-in-education/builds/543606436

Brought down link errors from 129 links to 5.
I don't understand whats happening with the remaining 5 links. The link with 404 for pygame works.
And other links keep changing.

**Comment by quobit** [comment]
Thanks a lot. I'll review all later.

**Comment by PandaWhoCodes** [comment]
Hey ?

**Comment by quobit** [comment]
Yes, I've been busy lately. Will check all changes this week (I've seen some false positives by awesome_bot/Travis). Lot of thanks for your work!

**Comment by quobit** [comment]
Hi @PandaWhoCodes !

I've reviewed your changes. First of all, again many many thanks for your work. I'd only suggest what follows:

**awesome_bot return some false linkrot, e.g.:**

- line 54 (1st link works. 2nd one changes to http://runestoneinteractive.org/pages/library.html)
- line 112 (it works)
- line 176 (redirects to safari but it works)
- line 205 (maybe fails due to more latency being a PDF)
- lines 435-438 (they work)

**OTOH, I'd also like to suggest:**

- (old) line 332: [JupyterLab Documentation](http://jupyterlab-tutorial.readthedocs.io/), just remove "-tutorial"
- line 329: don't understand why the change to gke.mybinder.org
- line 398: don't force to subscribe (delete "?sub_confirmation=1" at the end)

**Comment by quobit** [comment]
Partially solved by  281dd3e

**Comment by quobit** [comment]
Partially solved by  281dd3e

**Pull request closed without merging**
