### PR TITLE
Add Python Land and Ursina Engine

### PR DESCRIPTION
**Pull request by Danix421**
Hi, there! I'm Danix, a Python developer. Sorry if my english is bad, but i only speak spanish. I viewed Awesome Python in Education, thanks to the GitHub recomendations, and, like others, i wanted to contribute. For my contribution i added Python Land, a Python community (that appears to be alone), with a really good Python tutorial. Also, i added Ursina Engine, a Panda3D based engine that is configured to be (and it's) really easy-to-use. Well that is my contribution! I know it's not much but i added things that are tested, by me and other persons. Well, i hope Awesome Python in Education accept it!

### CODE REVIEW

**Comment by quobit** [comment]
Ursina project URL doesn't work. You should add www.

**Comment by Danix421** [comment]
> Ursina project URL doesn't work. You should add www.

Ok, i will fix it... now!

**Comment by Danix421** [comment]
> Ursina project URL doesn't work. You should add www.

Ok, it's now fixed.

**Comment by quobit** [comment]
Thanks! 🍰  🐍

**Comment by Danix421** [comment]
> Thanks!

Thanks for accepting my contribution! I hope in a near future i can contribute again.

**Pull request merged**
